/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamePackage;

import javax.swing.JLabel;


/*
 * #%L
 * UysalProject
 * %%
 * Copyright (C) 2016 Puzzle Inc.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */
/**
 * This class is puzzle game form, It holds positions of the game objects, apply
 * images to the labels.
 *
 * @author Oskay
 */
public class Puzzle extends javax.swing.JFrame {

    public static int firstRow, firstCol;
    public static boolean firstMove = false;

    /**
     * Layout of the puzzle game, 3 is border, 2 is goal, 1 is coin, 0 is empty square.
     */
    public static int squareArrays[][] = {
        {3, 3, 3, 3, 3, 3},
        {3, 2, 0, 0, 2, 3},
        {3, 0, 1, 1, 0, 3},
        {3, 0, 1, 1, 0, 3},
        {3, 2, 0, 0, 2, 3},
        {3, 3, 3, 3, 3, 3}};

    /**
     * Creates new form Puzzle
     */
    public Puzzle() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        refresh();
        usernaeLabel.setText("Good Luck, " + Main.username);

    }

    /**
     * Refresh every images and set the current score.
     */
    public void refresh() {
        label1_1.setIcon(IconManager.icon(1, 1));
        label1_2.setIcon(IconManager.icon(1, 2));
        label1_3.setIcon(IconManager.icon(1, 3));
        label1_4.setIcon(IconManager.icon(1, 4));
        label2_1.setIcon(IconManager.icon(2, 1));
        label2_2.setIcon(IconManager.icon(2, 2));
        label2_3.setIcon(IconManager.icon(2, 3));
        label2_4.setIcon(IconManager.icon(2, 4));
        label3_1.setIcon(IconManager.icon(3, 1));
        label3_2.setIcon(IconManager.icon(3, 2));
        label3_3.setIcon(IconManager.icon(3, 3));
        label3_4.setIcon(IconManager.icon(3, 4));
        label4_1.setIcon(IconManager.icon(4, 1));
        label4_2.setIcon(IconManager.icon(4, 2));
        label4_3.setIcon(IconManager.icon(4, 3));
        label4_4.setIcon(IconManager.icon(4, 4));
        scoreLabel.setText("Move Left: " + RuleManager.score);
        //RuleManager.isFinish();

        /*System.out.println("--------------------");
        for (int i = 1; i <= 4; i++) {
            for (int j = 1; j <= 4; j++) {
                System.out.println("i = " + i + " j = " + j + " Value = " + squareArrays[i][j]);

            }
        }
        System.out.println("--------------------");*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label3_4 = new javax.swing.JLabel();
        label3_1 = new javax.swing.JLabel();
        label3_3 = new javax.swing.JLabel();
        label3_2 = new javax.swing.JLabel();
        label4_1 = new javax.swing.JLabel();
        label4_2 = new javax.swing.JLabel();
        label4_3 = new javax.swing.JLabel();
        label4_4 = new javax.swing.JLabel();
        label2_1 = new javax.swing.JLabel();
        label2_2 = new javax.swing.JLabel();
        label1_1 = new javax.swing.JLabel();
        label1_2 = new javax.swing.JLabel();
        label2_3 = new javax.swing.JLabel();
        label1_3 = new javax.swing.JLabel();
        label2_4 = new javax.swing.JLabel();
        label1_4 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        usernaeLabel = new javax.swing.JLabel();
        goMainButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Puzzle Game");

        label3_4.setText("jLabel1");
        label3_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label3_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3_4MouseClicked(evt);
            }
        });

        label3_1.setText("jLabel1");
        label3_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label3_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3_1MouseClicked(evt);
            }
        });

        label3_3.setText("jLabel1");
        label3_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label3_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3_3MouseClicked(evt);
            }
        });

        label3_2.setText("jLabel1");
        label3_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label3_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3_2MouseClicked(evt);
            }
        });

        label4_1.setText("jLabel1");
        label4_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label4_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4_1MouseClicked(evt);
            }
        });

        label4_2.setText("jLabel1");
        label4_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label4_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4_2MouseClicked(evt);
            }
        });

        label4_3.setText("jLabel1");
        label4_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label4_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4_3MouseClicked(evt);
            }
        });

        label4_4.setText("jLabel1");
        label4_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label4_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4_4MouseClicked(evt);
            }
        });

        label2_1.setText("jLabel1");
        label2_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label2_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2_1MouseClicked(evt);
            }
        });

        label2_2.setText("jLabel1");
        label2_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label2_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2_2MouseClicked(evt);
            }
        });

        label1_1.setText("jLabel1");
        label1_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label1_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1_1MouseClicked(evt);
            }
        });

        label1_2.setText("jLabel1");
        label1_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label1_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1_2MouseClicked(evt);
            }
        });

        label2_3.setText("jLabel1");
        label2_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label2_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2_3MouseClicked(evt);
            }
        });

        label1_3.setText("jLabel1");
        label1_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label1_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1_3MouseClicked(evt);
            }
        });

        label2_4.setText("jLabel1");
        label2_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label2_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2_4MouseClicked(evt);
            }
        });

        label1_4.setText("jLabel1");
        label1_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label1_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1_4MouseClicked(evt);
            }
        });

        scoreLabel.setText("Score: ");

        usernaeLabel.setText("jLabel1");

        goMainButton.setText("Go To Main Menu");
        goMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goMainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(goMainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(usernaeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel)
                    .addComponent(goMainButton)
                    .addComponent(usernaeLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        scoreLabel.getAccessibleContext().setAccessibleName("scoreLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label1_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1_1MouseClicked

        RuleManager.Rules(1, 1);
        refresh();


    }//GEN-LAST:event_label1_1MouseClicked

    private void label1_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1_2MouseClicked

        RuleManager.Rules(1, 2);
        refresh();

    }//GEN-LAST:event_label1_2MouseClicked

    private void label1_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1_3MouseClicked

        RuleManager.Rules(1, 3);
        refresh();

    }//GEN-LAST:event_label1_3MouseClicked

    private void label1_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1_4MouseClicked

        RuleManager.Rules(1, 4);
        refresh();


    }//GEN-LAST:event_label1_4MouseClicked

    private void label2_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2_1MouseClicked

        RuleManager.Rules(2, 1);
        refresh();


    }//GEN-LAST:event_label2_1MouseClicked

    private void label2_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2_2MouseClicked

        RuleManager.Rules(2, 2);
        refresh();


    }//GEN-LAST:event_label2_2MouseClicked

    private void label2_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2_3MouseClicked

        RuleManager.Rules(2, 3);
        refresh();


    }//GEN-LAST:event_label2_3MouseClicked

    private void label2_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2_4MouseClicked

        RuleManager.Rules(2, 4);
        refresh();


    }//GEN-LAST:event_label2_4MouseClicked

    private void label3_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3_1MouseClicked

        RuleManager.Rules(3, 1);
        refresh();


    }//GEN-LAST:event_label3_1MouseClicked

    private void label3_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3_2MouseClicked

        RuleManager.Rules(3, 2);
        refresh();


    }//GEN-LAST:event_label3_2MouseClicked

    private void label3_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3_3MouseClicked

        RuleManager.Rules(3, 3);
        refresh();


    }//GEN-LAST:event_label3_3MouseClicked

    private void label3_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3_4MouseClicked

        RuleManager.Rules(3, 4);
        refresh();


    }//GEN-LAST:event_label3_4MouseClicked

    private void label4_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4_1MouseClicked

        RuleManager.Rules(4, 1);
        refresh();


    }//GEN-LAST:event_label4_1MouseClicked

    private void label4_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4_2MouseClicked

        RuleManager.Rules(4, 2);
        refresh();


    }//GEN-LAST:event_label4_2MouseClicked

    private void label4_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4_3MouseClicked

        RuleManager.Rules(4, 3);
        refresh();


    }//GEN-LAST:event_label4_3MouseClicked

    private void label4_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4_4MouseClicked

        RuleManager.Rules(4, 4);
        refresh();


    }//GEN-LAST:event_label4_4MouseClicked

    private void goMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goMainButtonActionPerformed
        this.setVisible(false);
        RuleManager.score = 100;
        for (int i = 1; i <= 4; i++) {
            for (int j = 1; j <= 4; j++) {
                squareArrays[i][j] = 0;
            }
        }
        squareArrays[2][2] = 1;
        squareArrays[2][3] = 1;
        squareArrays[3][2] = 1;
        squareArrays[3][3] = 1;
        squareArrays[1][1] = 2;
        squareArrays[4][1] = 2;
        squareArrays[1][4] = 2;
        squareArrays[4][4] = 2;
        RuleManager.counter = 0;
        new Main().setVisible(true);
    }//GEN-LAST:event_goMainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puzzle().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goMainButton;
    private javax.swing.JLabel label1_1;
    private javax.swing.JLabel label1_2;
    private javax.swing.JLabel label1_3;
    private javax.swing.JLabel label1_4;
    private javax.swing.JLabel label2_1;
    private javax.swing.JLabel label2_2;
    private javax.swing.JLabel label2_3;
    private javax.swing.JLabel label2_4;
    private javax.swing.JLabel label3_1;
    private javax.swing.JLabel label3_2;
    private javax.swing.JLabel label3_3;
    private javax.swing.JLabel label3_4;
    private javax.swing.JLabel label4_1;
    private javax.swing.JLabel label4_2;
    private javax.swing.JLabel label4_3;
    private javax.swing.JLabel label4_4;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel usernaeLabel;
    // End of variables declaration//GEN-END:variables
}
